version: '3'
services:
  mongodb:
    image: mongo
    # platform: linux/amd64
    # restart: always
    ports:
      - '27017:27017'
  redis:
    image: redis
    ports:
      - '6379:6379'
  emaily:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    # depends_on:
    #   - mongodb
    #   - redis
    # links:
    #   - mongodb
    #   - redis