name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.5.1"]

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
    
    env:
      NODE_ENV: ci
      PORT: 3000
      CI: false
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      REDIS: ${{ secrets.REDIS }}
      COOKIE_KEY: ${{ secrets.COOKIE_KEY }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
      API: ${{ secrets.API }}
      WEB: ${{ secrets.WEB }}
      MAILER_FROM: ${{ secrets.MAILER_FROM }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install
          npm install --prefix client
          npm run build --prefix client
      - name: Start server
        run: |
          nohup npm run start &
          sleep 3
      - name: Run tests
        run: npm run test